version: '3'
services:
  moon20x:
    image: moon20x:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - RUST_BACKTRACE=full
    ports:
      - 3012:3012

  redis:
    image: redis:3.2
    volumes:
      - "/data"
